### ISSUE TITLE
Alpha-equivalence

### ISSUE THREAD

**Issue by jamescheney** [jstolarek/inferno#15] opened 2020-11-26 16:06 UTC
Consider the following examples:

```
(* fml_alpha_equiv_1 *)
  let (x : (∀ a.  a → a) → int) = λ(y: ∀ a.  a → a)). 42 in
  let (z : ∀ b.  b → b) =  λw. w in
  x (~z)
(* fml_alpha_equiv_2 *)
  let (x : (∀ a.∀ b.  a → a) → int) = λ(y:∀ a.∀ b.  a → a). 42 in
  let (z : ∀ c.∀ d.  c → c) =  λw. w in
  x (~z)
 (* fml_alpha_equiv_3 *)
  let (x : (∀ a.∀ b.  b → b) → int) = λ(y:∀ a.∀ b.  b → b). 42 in
  let (z : ∀ c.∀ d.  d → d) =  λw. w in
  x (~z)
(* fml_alpha_equiv_4 *)
  let (x : (∀ a.∀ a.  a → a) → int) = λy(y:∀ a.∀ a.  a → a). 42 in
  let (z : ∀ b.∀ b.  b → b) =  λw. w in
  x (~z)
(* fml_alpha_equiv_5 *)
  let (x : (∀ a.∀ a.  a → a) → int) = λ(y:∀ a.∀ a.  a → a). 42 in
  let (z : ∀ a.∀ b.  a → a) =  λw. w in
  x (~z)
```
They should all work, naively, in FreezeML, except the last one, and perhaps the fourth and fifth examples should be alpha-renamed first before processing.  

Currently (4e19f88) all but the first one fail with implementation bugs.

**Comment by jstolarek** [comment] 2020-11-30 12:54
`fml_alpha_equiv_1` works as expected - I assume reporting it as not working was an oversight.

`fml_alpha_equiv_2` and `fml_alpha_equiv_3` failed because information about the quantifiers in the signature was not propagated to the inferred term, resulting in missing big-lambda abstractions in generated System F terms. Fixed in 480fc41.

`fml_alpha_equiv_4` failed because duplicate quantifiers were dropped. This was required to ensure that definitions like `choose` typecheck correctly. But there's a better and much simpler solution. When dealing with type signatures just discard generalizable variables from the generalisation engine and use the ones from the signature. This approach actually simplifies code. Fixed in 91b5c23.

In `fml_alpha_equiv_5` we check the looked up type of argument of `x` (`∀ a.∀ a. a → a`) against the frozen type of `z` (`∀ a.∀ b. a → a`) and there's nothing stopping the unification of `a` with `a` and then `a` with `b`. As a result we generate a System F term and the System F typechecker realizes that types `∀ a.∀ a. a → a` and `∀ a.∀ b. a → a` are different in de Bruijn representation. I suspect that a solution here would be to skolemize quantifiers of the frozen variable, but that solution is currently blocked by #11. This is because quantifiers on the argument of `x` (i.e. quantifiers in the type `∀ a.∀ a. a → a`) are already *incorrectly* skolemized because they appear in type annotation in a lambda and are not unskolemized later. So while this particular example would be fixed by skolemizing quantifiers in a frozen type many correct examples would be broken. Consider `fml_alpha_equiv_1`:

```
let (x : (∀ a. a → a) → Int) = λ(y: ∀ a. a → a)). 1 in
let (z : ∀ b. b → b) = λw. w in
x (~z)
```

Quantifier `a` in `∀ a. a → a` is incorrectly skolemized. If we now skolemize quantifier of `~z` the types will not unify and the example will fail. So I think dealing with this requires resolving #11 first.

**Comment by jstolarek** [comment] 2020-11-30 13:31
Ok, done now. The solution to #11 is not to skolemize the quantifiers in an annotated binder at all. Skolemization of quantifiers in a frozen type now handles all the cases correctly. See #11 for details.

**Comment by jamescheney** [comment] 2020-11-30 14:03
> fml_alpha_equiv_1 works as expected - I assume reporting it as not working was an oversight.

I didn't report it as not working.  What I wrote was probably a bit unclear:

> Currently (4e19f88) all but the first one fail with implementation bugs.

but the above does mean that `fml_alpha_equiv_1` works as expected while the other four examples fail with implementation bugs.

**Comment by jstolarek** [comment] 2020-11-30 14:22
My bad, sorry. Importantly, it works :-)

**Comment by jstolarek** [comment] 2020-12-01 13:08
>  When dealing with type signatures just discard generalizable variables from the generalisation engine and use the ones from the signature.

This is actually wrong, but a testsuite bug (ee4c13400a0718a3ca47287c59695e5327466c37) hid the problem. Consider `fml_id_annot_4` test:

```
let (y : ∀ a. a → a) = ~id in y
```

Here it is crucial that we don't have a big-lambda abstraction in the bound term, but my solution of grabbing the quantifiers from the annotation does exactly that. Consider this new `fml_alpha_equiv_6`:

```
let (x : (∀ a.∀ b. b → b) → Int) = λ(y:∀ a. ∀ b. b → b). 1 in
let (z : ∀ c.∀ d. d → d) = ~id in
x (~z)
```

This differs from `fml_alpha_equiv_3` in the definition of `z` and currently fails for the same reason as `fml_id_annot_4`.

**Comment by jstolarek** [comment] 2020-12-03 16:46
As discussed in a hangouts call with @jamescheney, we need to double-check which of these definitions should type check in FreezeML (per PLDI specification):

```
let (z : ∀ a. ∀ b. b → b) = λw. w in ...
let (z : ∀ a. ∀ b. b → b) = id in ...
let (z : ∀ a. ∀ b. b → b) = ~id in 
```

In case anyone other than myself ends up debugging this here's an important note. In inferno we maintain an environment of bindings and their associated type schemes represented as a a record `{ quantifiers; body }`, where `quantifiers` is a list of generic variables with no structure and `body` is a generic variable (most likely with a structure). Now, of course with first-class polymorphism we shouldn't really distinguish type schemes in any special way, but we do that internally in inferno since it's a convenient data representation. However, we can also have quantifiers nested inside variable structure. In other words, if a binding has type `∀ a. a → a` it can be represented as `{ quantifiers = [a], body = a → a }`, but it could also be represented as `{ quantifiers = [], body = ∀ a. a → a }`, i.e. top-level quantifiers can be stored inside the `body` structure. There is a function [`Generalize.scheme`](https://github.com/jstolarek/inferno/blob/freezemlx/src/Generalization.ml#L177) that extracts these nested quantifiers to the top-level to ensure a "canonical" scheme representation. This function is applied eagerly in several places, but it might turn that getting the above examples right requires more thought in how that function is applied.

**Comment by frank-emrich** [comment] 2020-12-05 19:41
To answer your question regarding the three examples w.r.t. PLDI FreezeML:
1. does typecheck
2. does typecheck
3. does not typecheck

**Comment by jstolarek** [comment] 2020-12-05 19:49
Thanks. Me and @jamescheney  suspected this to be the case but wanted to make sure.

**Comment by frank-emrich** [comment] 2020-12-05 20:14
In particular, this means that `fml_alpha_equiv_6` should be rejected.

The problem is that when designing the PLDI inference algorithm, we needed to come up with an answer to the following question:
In an annotated let binding
let (x : ∀ \Delta.H) = M in N 
how do we decide which type variables in \Delta are already "present" in the type of M (e.g., if M is a frozen variable), and which ones come from generalization done by the let binding itself?
In the PLDI inference algorithm, we need to know this before inferring the type of M, because we need to know the in-scope rigid type variables before inferring the type of M. In figure 16 of the PLDI paper, this is seen by us calling `infer` with Delta, \Delta' as the updated rigid environment.

To solve the problem, we decided that it is never possible that some of the quantifiers in the annotation stem from the term itself, while some come from generalization. Instead, the rules are as follows:
1. For generalizable terms, all quantifiers come from generalization
2. For non-generalizable terms (to which we count frozen vars), all of the quantifiers come from the term itself.

Now in FreezeML(X), we eschew the value restriction (yielding typing rules as shown in appendix F.2 of the ML workshop paper on Explicit FreezeML, where we presented a version of FreezeML without the VR). This means that we would also apply the first rule to frozen variables. This would mean that type annotations on frozen variables are only possible if the variable has a guarded type (in which case the freezing is useless anyway).

I will have to re-think/remember if it is possible to design an inference algorithm for a variant of the PLDI type system that doesn't need to know the rigid variables ahead of time or if this would cause fundamental problems. Or in other words, it would be interesting to see if this is only something to make the inference algorithm simpler or something that is fundamentally required.

**Comment by jstolarek** [comment] 2020-12-07 15:25
Thanks. This explanation saved me a lot of time.

> In the PLDI inference algorithm, we need to know this before inferring the type of M, because we need to know the in-scope rigid type variables before inferring the type of M.

As you probably already seen in the code at the moment this isn't the case in inferno. In inferno we infer the type of M independently of the signature and only then check whether the signature is an instance of that type.

**Comment by frank-emrich** [comment] 2020-12-08 19:57
> As you probably already seen in the code at the moment this isn't the case in inferno.

I think that's actually a good thing! I suspect that it would have been possible to design a variant of the Algorithm W based FreezeML inference algorithm that does not need to know this ahead of time. I think one of the reasons we didn't try very hard to do this for the FreezeML PLDI version was that it definitely complicates the typing rule for annotated let. That is a bit unsatisfying, because this is a place where us not treating types equivalent modulo reordering of type variables and adding/removing superfluous ones actually makes things more complicated, even though we always claimed that not allowing this was a design choice to make things simpler.

I've also drafted a variant of FreezeML that does treat such types as equivalent, but without thinking about type inference a lot (because it is pretty straightforward to see that there *exists* a variant of our original algorithm that supports this because it normalizes all types in any step, even if that's not vert practical). This is mostly to show that our system supports this line of thought, because it's something that we were regularly criticized for. I would still consider the variant of FreezeML that does care about variable ordering as the "true" FreezeML because Explicit FreezeML heavily relies on this.

**Closed** 2020-12-11 12:13 UTC
